-- =============================================================================
-- gerirfrota — init.sql
-- Schema completo do banco. Roda 1 vez por instância (cidade).
-- Compatível com Supabase (Postgres 15+) — usa auth.users / auth.uid().
-- =============================================================================

create extension if not exists pgcrypto;

-- =============================================================================
-- ENUMS
-- =============================================================================
create type user_role            as enum ('admin','usuario','fornecedor');
create type supplier_kind        as enum ('posto','mecanica','ambos');
create type authorization_status as enum ('emitida','utilizada','cancelada');
create type maintenance_kind     as enum ('preventiva','corretiva','revisao','sinistro','outros');
create type maintenance_status   as enum ('aberta','em_andamento','concluida','cancelada');

-- =============================================================================
-- HELPER: trigger genérico de updated_at
-- =============================================================================
create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =============================================================================
-- LOOKUPS TCE-PI (populadas via dump.sql)
-- =============================================================================
create table ibge_municipality (
  code char(7) primary key,
  name text not null unique
);

create table vehicle_type (
  code smallint primary key,
  description text not null,
  notes text
);

create table fuel_type (
  code smallint primary key,
  description text not null
);

-- Subtipos comerciais (Diesel S10, Gasolina Aditivada, etc.) — só UX interna.
-- TCE-PI não conhece subtipos; exportações TCE usam o fuel_type_code pai.
create table fuel_subtype (
  id smallint primary key generated by default as identity,
  fuel_type_code smallint not null references fuel_type(code),
  description text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index ix_fuel_subtype_parent on fuel_subtype (fuel_type_code) where active;

create table vehicle_origin (
  code smallint primary key,
  description text not null
);

create table sim_nao (
  code smallint primary key,
  description text not null
);

-- =============================================================================
-- ENTITY (singleton — 1 cidade = 1 instância)
-- =============================================================================
create table entity (
  id smallint primary key default 1 check (id = 1),
  entity_type text not null,
  ibge_code char(7) not null references ibge_municipality(code),
  organ_name text not null,
  coat_of_arms_url text,
  default_ref_month char(7),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_entity_set_updated_at before update on entity
  for each row execute function set_updated_at();

-- =============================================================================
-- DEPARTMENT (secretarias / órgãos)
-- =============================================================================
create table department (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  acronym text not null unique,
  cost_center text,
  responsible_name text,
  phone text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_department_set_updated_at before update on department
  for each row execute function set_updated_at();
create index ix_department_acronym on department (acronym);

-- =============================================================================
-- VEHICLE
-- =============================================================================
create table vehicle (
  id uuid primary key default gen_random_uuid(),
  internal_code text unique,
  plate text not null,
  renavam char(11) not null,
  chassis text,
  model text not null,
  brand text,
  year_manufacture smallint not null,
  year_model smallint not null,
  vehicle_type_code smallint not null references vehicle_type(code),
  fuel_type_code smallint not null references fuel_type(code),
  fuel_subtype_id smallint references fuel_subtype(id),
  vehicle_origin_code smallint not null references vehicle_origin(code),
  department_id uuid references department(id),
  tank_capacity numeric(5,2) check (tank_capacity is null or (tank_capacity > 0 and tank_capacity < 1000)),
  current_km integer not null default 0 check (current_km >= 0 and current_km <= 99999999),
  conservation_state text,
  acquisition_date date,
  notes text,
  -- cedido (origem 2)
  cession_destination_organ text,
  cession_start_date date,
  cession_end_date date,
  -- locado/sublocado (origem 3/4)
  lessor_doc text,
  lessor_name text,
  monthly_value numeric(15,2),
  has_driver boolean,
  cw_contract_code text,
  -- datas do contrato de locação (uso interno; TCE 443 não exige, filtros usam)
  lessor_lease_start_date date,
  lessor_lease_end_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  constraint chk_years_consistent  check (year_manufacture <= year_model),
  constraint chk_year_mfg_max      check (year_manufacture <= extract(year from current_date)::int),
  constraint chk_year_mdl_max      check (year_model       <= extract(year from current_date)::int + 1),
  constraint chk_plate_format      check (plate ~ '^([A-Z]{3}[0-9]{4}|[A-Z]{3}[0-9][A-Z][0-9]{2})$'),
  constraint chk_renavam_digits    check (renavam ~ '^[0-9]{11}$'),

  -- TCE 517 §1.1.8 / §1.1.9
  constraint chk_outros_consistency check (
    (vehicle_type_code = 99
       and renavam = '99999999999'
       and plate like 'XYZ%')
    or (vehicle_type_code <> 99
       and renavam <> '99999999999'
       and plate not like 'XYZ%')
  ),

  -- TCE 503 §1.1.4 / §1.1.5
  -- TCE 503: orgaoDestVeicCedido / dataInicCessao / dataFimCessao são opcionais
  -- mesmo quando cedido. Quando ambas as datas estiverem preenchidas, valida ordem.
  constraint chk_cession_dates check (
    cession_end_date is null or cession_start_date is null
    or cession_end_date >= cession_start_date
  ),

  -- TCE 443 (cadastro completo)
  constraint chk_lease_required_fields check (
    vehicle_origin_code not in (3,4)
    or (
      lessor_doc ~ '^([0-9]{11}|[0-9]{14})$'
      and lessor_name is not null
      and monthly_value > 0
      and has_driver is not null
      and cw_contract_code ~ '^CW-[0-9]{6}/[0-9]{2}$'
    )
  ),
  -- v4: datas de locação coerentes quando ambas preenchidas
  constraint chk_lease_dates check (
    lessor_lease_end_date is null
    or lessor_lease_start_date is null
    or lessor_lease_end_date >= lessor_lease_start_date
  )
);
create trigger trg_vehicle_set_updated_at before update on vehicle
  for each row execute function set_updated_at();
create unique index ux_vehicle_plate_active on vehicle (plate) where deleted_at is null;
create index ix_vehicle_origin     on vehicle (vehicle_origin_code) where deleted_at is null;
create index ix_vehicle_department on vehicle (department_id)       where deleted_at is null;

-- =============================================================================
-- SUPPLIER (posto e/ou mecânica)
-- =============================================================================
create table supplier (
  id uuid primary key default gen_random_uuid(),
  kind supplier_kind not null default 'posto',
  legal_name text not null,
  trade_name text,
  cnpj char(14) not null check (cnpj ~ '^[0-9]{14}$') unique,
  responsible_name text,
  phone text,
  address text,
  city text,
  ibge_code char(7) references ibge_municipality(code),
  -- v5: secretaria de origem do contrato + nº/ano do contrato
  department_id uuid references department(id),
  contract_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_supplier_set_updated_at before update on supplier
  for each row execute function set_updated_at();
create index ix_supplier_kind on supplier (kind);
create index ix_supplier_department on supplier (department_id);

-- =============================================================================
-- SUPPLIER_FUEL (contrato por combustível)
-- contract_amount = 0 → ilimitado
-- =============================================================================
create table supplier_fuel (
  id uuid primary key default gen_random_uuid(),
  supplier_id uuid not null references supplier(id) on delete cascade,
  fuel_type_code smallint not null references fuel_type(code),
  fuel_subtype_id smallint references fuel_subtype(id),
  unit_price numeric(8,3) not null check (unit_price >= 0),
  contract_amount numeric(12,2) not null default 0 check (contract_amount >= 0),
  current_balance numeric(12,2) not null default 0 check (current_balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_balance_within_contract check (
    contract_amount = 0 or current_balance <= contract_amount
  )
);
-- Unicidade por supplier+fuel+subtype (subtype NULL conta como valor único via COALESCE)
create unique index ux_supplier_fuel_unique
  on supplier_fuel (supplier_id, fuel_type_code, coalesce(fuel_subtype_id, 0::smallint));
create trigger trg_supplier_fuel_set_updated_at before update on supplier_fuel
  for each row execute function set_updated_at();

-- =============================================================================
-- APP_USER (perfil ligado a auth.users do Supabase)
-- =============================================================================
create table app_user (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique
    check (username ~ '^[a-z0-9._-]{3,30}$'),
  full_name text not null,
  role user_role not null,
  access_start date,
  access_end date,
  supplier_id uuid references supplier(id) on delete set null,
  monthly_authorization_limit numeric(12,2) not null default 0
    check (monthly_authorization_limit >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_access_period check (
    access_end is null or access_start is null or access_end >= access_start
  ),
  constraint chk_supplier_only_for_supplier_role check (
    (role = 'fornecedor' and supplier_id is not null)
    or (role <> 'fornecedor' and supplier_id is null)
  )
);
create trigger trg_app_user_set_updated_at before update on app_user
  for each row execute function set_updated_at();

-- Resolve username → email para login (front chama antes do signInWithPassword).
-- security definer: ignora RLS de auth.users; acessível por anon (pré-login) e authenticated.
create or replace function email_from_username(p_username text)
returns text
language sql security definer set search_path = public, auth as $$
  select u.email
  from app_user au
  join auth.users u on u.id = au.id
  where au.username = lower(p_username) and au.active = true
$$;
revoke all on function email_from_username(text) from public;
grant execute on function email_from_username(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- ADMIN: gerenciamento de usuários via RPC (sem Edge Function).
-- ---------------------------------------------------------------------------
create or replace function _require_admin() returns void
language plpgsql security definer set search_path = public as $$
declare v_role user_role; v_active boolean;
begin
  select role, active into v_role, v_active from app_user where id = auth.uid();
  if v_role is null then raise exception 'Sessão inválida' using errcode = '28000'; end if;
  if v_role <> 'admin' or not v_active then
    raise exception 'Apenas administradores ativos podem executar esta ação' using errcode = '42501';
  end if;
end;
$$;
revoke all on function _require_admin() from public;
grant execute on function _require_admin() to authenticated;

create or replace function admin_create_user(
  p_email text, p_password text, p_username text, p_full_name text, p_role user_role,
  p_supplier_id uuid default null, p_access_start date default null,
  p_access_end date default null, p_monthly_authorization_limit numeric default 0
) returns uuid
language plpgsql security definer set search_path = public, auth as $$
declare v_user_id uuid := gen_random_uuid();
begin
  perform _require_admin();
  if p_email is null or position('@' in p_email) = 0 then raise exception 'Email inválido' using errcode = '22023'; end if;
  if p_password is null or length(p_password) < 6 then raise exception 'Senha deve ter ao menos 6 caracteres' using errcode = '22023'; end if;
  if p_username !~ '^[a-z0-9._-]{3,30}$' then raise exception 'Username inválido (3-30 chars, [a-z0-9._-])' using errcode = '22023'; end if;
  if exists (select 1 from app_user where username = p_username) then raise exception 'Username já em uso' using errcode = '23505'; end if;
  if exists (select 1 from auth.users where email = p_email) then raise exception 'Email já em uso' using errcode = '23505'; end if;
  if p_role = 'fornecedor' and p_supplier_id is null then raise exception 'Fornecedor exige supplier_id' using errcode = '22023'; end if;

  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
    confirmation_token, email_change, email_change_token_new, recovery_token
  ) values (
    '00000000-0000-0000-0000-000000000000', v_user_id, 'authenticated', 'authenticated',
    p_email, extensions.crypt(p_password, extensions.gen_salt('bf')), now(),
    jsonb_build_object('provider','email','providers',jsonb_build_array('email')),
    jsonb_build_object('full_name', p_full_name), now(), now(), '', '', '', ''
  );
  insert into auth.identities (
    id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
  ) values (
    gen_random_uuid(), v_user_id, v_user_id::text,
    jsonb_build_object('sub', v_user_id::text, 'email', p_email, 'email_verified', true),
    'email', now(), now(), now()
  );
  insert into app_user (
    id, username, full_name, role, supplier_id,
    access_start, access_end, monthly_authorization_limit, active
  ) values (
    v_user_id, p_username, p_full_name, p_role,
    case when p_role = 'fornecedor' then p_supplier_id else null end,
    p_access_start, p_access_end, coalesce(p_monthly_authorization_limit, 0), true
  );
  return v_user_id;
end;
$$;
revoke all on function admin_create_user(text,text,text,text,user_role,uuid,date,date,numeric) from public;
grant execute on function admin_create_user(text,text,text,text,user_role,uuid,date,date,numeric) to authenticated;

create or replace function admin_delete_user(p_user_id uuid) returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  perform _require_admin();
  if p_user_id = auth.uid() then raise exception 'Você não pode excluir o próprio usuário' using errcode = '42501'; end if;
  delete from auth.users where id = p_user_id;
  if not found then raise exception 'Usuário não encontrado' using errcode = '02000'; end if;
end;
$$;
revoke all on function admin_delete_user(uuid) from public;
grant execute on function admin_delete_user(uuid) to authenticated;

create or replace function admin_set_user_password(p_user_id uuid, p_new_password text) returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  perform _require_admin();
  if p_new_password is null or length(p_new_password) < 6 then
    raise exception 'Senha deve ter ao menos 6 caracteres' using errcode = '22023';
  end if;
  update auth.users
     set encrypted_password = extensions.crypt(p_new_password, extensions.gen_salt('bf')), updated_at = now()
   where id = p_user_id;
  if not found then raise exception 'Usuário não encontrado' using errcode = '02000'; end if;
end;
$$;
revoke all on function admin_set_user_password(uuid,text) from public;
grant execute on function admin_set_user_password(uuid,text) to authenticated;

create or replace function admin_list_users()
returns table (
  id uuid, username text, full_name text, role user_role, active boolean,
  supplier_id uuid, monthly_authorization_limit numeric,
  access_start date, access_end date, created_at timestamptz, email text
)
language plpgsql security definer set search_path = public, auth as $$
begin
  perform _require_admin();
  return query
    select au.id::uuid,
           au.username::text,
           au.full_name::text,
           au.role::user_role,
           au.active::boolean,
           au.supplier_id::uuid,
           au.monthly_authorization_limit::numeric,
           au.access_start::date,
           au.access_end::date,
           au.created_at::timestamptz,
           u.email::text
      from app_user au
      left join auth.users u on u.id = au.id
      order by au.created_at;
end;
$$;
revoke all on function admin_list_users() from public;
grant execute on function admin_list_users() to authenticated;

-- =============================================================================
-- FUELING_AUTHORIZATION
-- =============================================================================
create table fueling_authorization (
  id uuid primary key default gen_random_uuid(),
  number text not null unique,                     -- 'AAAAMMDD-NNN'
  date date not null,
  status authorization_status not null default 'emitida',
  vehicle_id uuid not null references vehicle(id),
  supplier_id uuid not null references supplier(id),
  fuel_type_code smallint not null references fuel_type(code),
  fuel_subtype_id smallint references fuel_subtype(id),
  authorized_quantity numeric(8,2) not null check (authorized_quantity > 0),
  unit_price_snapshot numeric(8,3) not null,
  estimated_total numeric(12,2) generated always as (authorized_quantity * unit_price_snapshot) stored,
  responsible_name text not null,
  notes text,
  -- snapshots de denormalização
  vehicle_plate_snapshot text not null,
  vehicle_model_snapshot text not null,
  department_acronym_snapshot text,
  supplier_trade_name_snapshot text not null,
  qr_payload text not null,
  created_by uuid references app_user(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create trigger trg_fueling_authorization_set_updated_at before update on fueling_authorization
  for each row execute function set_updated_at();
create index ix_auth_date     on fueling_authorization (date);
create index ix_auth_status   on fueling_authorization (status)      where deleted_at is null;
create index ix_auth_vehicle  on fueling_authorization (vehicle_id);
create index ix_auth_supplier on fueling_authorization (supplier_id);
create index ix_auth_resp     on fueling_authorization (responsible_name);

-- =============================================================================
-- FUELING (registro de consumo)
-- =============================================================================
create table fueling (
  id uuid primary key default gen_random_uuid(),
  authorization_id uuid references fueling_authorization(id),
  vehicle_id uuid not null references vehicle(id),
  supplier_id uuid not null references supplier(id),
  fuel_type_code smallint not null references fuel_type(code),
  fuel_subtype_id smallint references fuel_subtype(id),
  date date not null,
  quantity numeric(8,2) not null check (quantity > 0),
  unit_price numeric(8,3) not null check (unit_price >= 0),
  total numeric(12,2) generated always as (quantity * unit_price) stored,
  km_initial integer check (km_initial is null or (km_initial >= 0 and km_initial <= 99999999)),
  km_final   integer check (km_final   is null or (km_final   >= 0 and km_final   <= 99999999)),
  responsible_name text not null,
  notes text,
  vehicle_plate_snapshot text not null,
  department_acronym_snapshot text,
  supplier_trade_name_snapshot text not null,
  created_by uuid references app_user(id),
  filled_by_supplier_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint chk_km_order check (km_initial is null or km_final is null or km_initial <= km_final),
  -- TCE 517: campo combustivel_abastecimento aceita só ALCOOL/GASOLINA/DIESEL/GNV/ELETRICIDADE.
  -- FLEX (5) e HIBRIDO (7) são tipos do veículo, não do evento de abastecimento.
  constraint chk_fueling_fuel_kind check (fuel_type_code in (1,2,3,4,6))
);
create trigger trg_fueling_set_updated_at before update on fueling
  for each row execute function set_updated_at();
create index ix_fueling_date     on fueling (date);
create index ix_fueling_vehicle  on fueling (vehicle_id);
create index ix_fueling_supplier on fueling (supplier_id);
create index ix_fueling_auth     on fueling (authorization_id);

-- =============================================================================
-- MAINTENANCE
-- =============================================================================
create table maintenance (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references vehicle(id),
  supplier_id uuid references supplier(id),
  kind maintenance_kind not null,
  status maintenance_status not null default 'aberta',
  open_date date not null default current_date,
  close_date date,
  km_at_service integer check (km_at_service is null or km_at_service >= 0),
  description text not null,
  total_value numeric(12,2),
  responsible_name text,
  notes text,
  created_by uuid references app_user(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint chk_close_after_open check (close_date is null or close_date >= open_date)
);
create trigger trg_maintenance_set_updated_at before update on maintenance
  for each row execute function set_updated_at();
create index ix_maintenance_vehicle on maintenance (vehicle_id);
create index ix_maintenance_status  on maintenance (status) where deleted_at is null;

-- =============================================================================
-- TRIGGERS DE NEGÓCIO
-- =============================================================================

-- vehicle.current_km recebe o maior km_final lançado
create or replace function update_vehicle_km_from_fueling() returns trigger
language plpgsql as $$
begin
  if new.km_final is not null then
    update vehicle
      set current_km = greatest(current_km, new.km_final)
      where id = new.vehicle_id;
  end if;
  return new;
end;
$$;
create trigger trg_fueling_update_vehicle_km
  after insert or update on fueling
  for each row execute function update_vehicle_km_from_fueling();

-- TCE 517 §1.1.8: se veículo é tipo "Outros" (99), km do abastecimento = 99999999
create or replace function validate_fueling_outros_rule() returns trigger
language plpgsql as $$
declare v_type smallint;
begin
  select vehicle_type_code into v_type from vehicle where id = new.vehicle_id;
  if v_type = 99 then
    if new.km_initial is distinct from 99999999 or new.km_final is distinct from 99999999 then
      raise exception 'Veículo tipo OUTROS (99): km_initial e km_final do abastecimento devem ser 99999999';
    end if;
  else
    if new.km_initial = 99999999 or new.km_final = 99999999 then
      raise exception 'Veículo não-OUTROS não pode ter km_initial/km_final = 99999999 (sentinela reservada)';
    end if;
  end if;
  return new;
end;
$$;
create trigger trg_fueling_validate_outros
  before insert or update on fueling
  for each row execute function validate_fueling_outros_rule();

-- Abastecimento vinculado: qty ≤ autorizado, demais campos batem
create or replace function validate_fueling_against_authorization() returns trigger
language plpgsql as $$
declare
  a_qty numeric; a_veh uuid; a_sup uuid; a_fuel smallint;
begin
  if new.authorization_id is null then return new; end if;
  select authorized_quantity, vehicle_id, supplier_id, fuel_type_code
    into a_qty, a_veh, a_sup, a_fuel
    from fueling_authorization where id = new.authorization_id;
  if a_qty is null then
    raise exception 'Autorização % não encontrada', new.authorization_id;
  end if;
  if new.quantity > a_qty then
    raise exception 'Quantidade abastecida (% L) excede autorizado (% L)', new.quantity, a_qty;
  end if;
  if new.vehicle_id  <> a_veh  then raise exception 'Veículo divergente da autorização';     end if;
  if new.supplier_id <> a_sup  then raise exception 'Fornecedor divergente da autorização';  end if;
  if new.fuel_type_code <> a_fuel then raise exception 'Combustível divergente da autorização'; end if;
  return new;
end;
$$;
create trigger trg_fueling_validate_auth
  before insert or update on fueling
  for each row execute function validate_fueling_against_authorization();

-- Ao inserir fueling vinculado, autorização vira 'utilizada'
create or replace function mark_authorization_as_used() returns trigger
language plpgsql as $$
begin
  if new.authorization_id is not null then
    update fueling_authorization
      set status = 'utilizada'
      where id = new.authorization_id and status = 'emitida';
  end if;
  return new;
end;
$$;
create trigger trg_fueling_mark_auth_used
  after insert on fueling
  for each row execute function mark_authorization_as_used();

-- Ao deletar fueling vinculado, se for o último, autorização volta a 'emitida'
create or replace function revert_authorization_on_fueling_delete() returns trigger
language plpgsql as $$
declare n integer;
begin
  if old.authorization_id is null then return old; end if;
  select count(*) into n from fueling
    where authorization_id = old.authorization_id
      and id <> old.id and deleted_at is null;
  if n = 0 then
    update fueling_authorization
      set status = 'emitida'
      where id = old.authorization_id and status = 'utilizada';
  end if;
  return old;
end;
$$;
create trigger trg_fueling_revert_auth
  before delete on fueling
  for each row execute function revert_authorization_on_fueling_delete();

-- =============================================================================
-- RPCs (lógica transacional usada pelo front via supabase.rpc())
-- =============================================================================

-- Gera o próximo número de autorização do dia
create or replace function generate_authorization_number(p_date date) returns text
language plpgsql as $$
declare ds text; n int;
begin
  ds := to_char(p_date,'YYYYMMDD');
  select count(*)+1 into n from fueling_authorization where number like ds || '-%';
  return ds || '-' || lpad(n::text,3,'0');
end;
$$;

-- Emite autorização (valida tanque, saldo e limite mensal; debita saldo)
create or replace function emit_authorization(
  p_date date,
  p_vehicle_id uuid,
  p_supplier_id uuid,
  p_fuel_type_code smallint,
  p_quantity numeric,
  p_responsible_name text,
  p_notes text default null
) returns uuid
language plpgsql as $$
declare
  v_auth_id uuid;
  v_number  text;
  v_price   numeric(8,3);
  v_contract numeric; v_balance numeric;
  v_tank    numeric;
  v_user_limit numeric; v_month_used numeric; v_estimated numeric;
  v_plate text; v_model text; v_dept text; v_sup_name text; v_qr text;
  v_fuel_desc text;
begin
  -- Snapshots
  select plate, model, tank_capacity into v_plate, v_model, v_tank
    from vehicle where id = p_vehicle_id and deleted_at is null;
  if v_plate is null then raise exception 'Veículo não encontrado'; end if;

  select d.acronym into v_dept
    from vehicle v left join department d on d.id = v.department_id
    where v.id = p_vehicle_id;

  select coalesce(trade_name, legal_name) into v_sup_name
    from supplier where id = p_supplier_id;
  if v_sup_name is null then raise exception 'Fornecedor não encontrado'; end if;

  if v_tank is not null and p_quantity > v_tank then
    raise exception 'Quantidade % L excede capacidade do tanque (% L)', p_quantity, v_tank;
  end if;

  -- Preço, saldo
  select unit_price, contract_amount, current_balance
    into v_price, v_contract, v_balance
    from supplier_fuel
    where supplier_id = p_supplier_id and fuel_type_code = p_fuel_type_code;
  if v_price is null then
    raise exception 'Fornecedor não vende esse combustível';
  end if;
  if v_contract > 0 and p_quantity > v_balance then
    raise exception 'Saldo insuficiente: disponível % L, solicitado % L', v_balance, p_quantity;
  end if;
  v_estimated := p_quantity * v_price;

  -- Limite mensal do responsável (busca por nome — mesmo critério da UI)
  select monthly_authorization_limit into v_user_limit
    from app_user
    where full_name = p_responsible_name and active = true
    limit 1;
  if v_user_limit is not null and v_user_limit > 0 then
    select coalesce(sum(estimated_total),0) into v_month_used
      from fueling_authorization
      where responsible_name = p_responsible_name
        and status in ('emitida','utilizada')
        and date_trunc('month', date) = date_trunc('month', p_date)
        and deleted_at is null;
    if v_month_used + v_estimated > v_user_limit then
      raise exception 'Limite mensal do responsável excedido: limite R$%, usado R$%, nova R$%',
        v_user_limit, v_month_used, v_estimated;
    end if;
  end if;

  -- Número + QR
  v_number := generate_authorization_number(p_date);
  select description into v_fuel_desc from fuel_type where code = p_fuel_type_code;
  v_qr := format('AUT:%s|VEI:%s|COMB:%s|QTD:%sL|DATA:%s|SIT:emitida',
    v_number, v_plate, v_fuel_desc, p_quantity, to_char(p_date,'DD/MM/YYYY'));

  insert into fueling_authorization (
    number, date, vehicle_id, supplier_id, fuel_type_code,
    authorized_quantity, unit_price_snapshot, responsible_name, notes,
    vehicle_plate_snapshot, vehicle_model_snapshot,
    department_acronym_snapshot, supplier_trade_name_snapshot,
    qr_payload, created_by
  ) values (
    v_number, p_date, p_vehicle_id, p_supplier_id, p_fuel_type_code,
    p_quantity, v_price, p_responsible_name, p_notes,
    v_plate, v_model, v_dept, v_sup_name,
    v_qr, auth.uid()
  ) returning id into v_auth_id;

  -- Debita saldo
  if v_contract > 0 then
    update supplier_fuel
      set current_balance = current_balance - p_quantity
      where supplier_id = p_supplier_id and fuel_type_code = p_fuel_type_code;
  end if;

  return v_auth_id;
end;
$$;

-- Cancela autorização emitida (restaura saldo)
create or replace function cancel_authorization(p_auth_id uuid) returns void
language plpgsql as $$
declare v_sup uuid; v_fuel smallint; v_qty numeric; v_contract numeric;
begin
  select supplier_id, fuel_type_code, authorized_quantity
    into v_sup, v_fuel, v_qty
    from fueling_authorization
    where id = p_auth_id and status = 'emitida';
  if v_sup is null then raise exception 'Autorização não encontrada ou não está emitida'; end if;

  update fueling_authorization set status = 'cancelada' where id = p_auth_id;

  select contract_amount into v_contract from supplier_fuel
    where supplier_id = v_sup and fuel_type_code = v_fuel;
  if v_contract > 0 then
    update supplier_fuel
      set current_balance = least(contract_amount, current_balance + v_qty)
      where supplier_id = v_sup and fuel_type_code = v_fuel;
  end if;
end;
$$;

-- Ajusta quantidade da autorização emitida (delta no saldo)
create or replace function update_authorization_quantity(p_auth_id uuid, p_new_qty numeric) returns void
language plpgsql as $$
declare
  v_sup uuid; v_fuel smallint; v_old numeric; v_contract numeric; v_balance numeric; v_diff numeric;
begin
  if p_new_qty <= 0 then raise exception 'Quantidade deve ser > 0'; end if;

  select supplier_id, fuel_type_code, authorized_quantity
    into v_sup, v_fuel, v_old
    from fueling_authorization
    where id = p_auth_id and status = 'emitida';
  if v_sup is null then raise exception 'Autorização não encontrada ou não está emitida'; end if;

  v_diff := p_new_qty - v_old;
  if v_diff = 0 then return; end if;

  select contract_amount, current_balance into v_contract, v_balance
    from supplier_fuel
    where supplier_id = v_sup and fuel_type_code = v_fuel;

  if v_contract > 0 and v_diff > 0 and v_diff > v_balance then
    raise exception 'Saldo insuficiente para aumento: disponível % L', v_balance;
  end if;

  update fueling_authorization
    set authorized_quantity = p_new_qty
    where id = p_auth_id;

  if v_contract > 0 then
    update supplier_fuel
      set current_balance = least(contract_amount, current_balance - v_diff)
      where supplier_id = v_sup and fuel_type_code = v_fuel;
  end if;
end;
$$;

-- =============================================================================
-- VIEWS: exportações TCE-PI e relatórios internos
-- =============================================================================

-- 517 — Abastecimento (consolidado por veículo + combustível + mês)
create or replace view v_tce_517_abastecimento as
select
  v.model                              as "modelo",
  v.plate                              as "placa",
  v.renavam                            as "renavam",
  v.year_manufacture                   as "anoFabricacao",
  v.year_model                         as "anoModelo",
  v.vehicle_type_code                  as "tipoVeiculo",
  v.vehicle_origin_code                as "origemVeiculo",
  d.name                               as "orgaoLocalizacao",
  v.tank_capacity                      as "capacidade",
  sum(f.quantity)::numeric(10,2)       as "quantidadeAbastecimento",
  f.fuel_type_code                     as "tipoCombustivel",
  min(f.km_initial)                    as "kmInicial",
  max(f.km_final)                      as "kmFinal",
  to_char(f.date,'YYYY-MM')            as ref_month
from fueling f
join vehicle v on v.id = f.vehicle_id
left join department d on d.id = v.department_id
where f.deleted_at is null and v.deleted_at is null
group by v.id, v.model, v.plate, v.renavam, v.year_manufacture, v.year_model,
         v.vehicle_type_code, v.vehicle_origin_code, d.name, v.tank_capacity,
         f.fuel_type_code, to_char(f.date,'YYYY-MM');

-- 503 — Próprios e Cedidos
create or replace view v_tce_503_proprios_cedidos as
select
  v.model                                                as "modelo",
  v.plate                                                as "placa",
  v.renavam                                              as "renavam",
  v.year_manufacture                                     as "anoFabricacao",
  v.year_model                                           as "anoModelo",
  v.fuel_type_code                                       as "tipoCombustivel",
  v.conservation_state                                   as "estadoConservacao",
  e.ibge_code                                            as "localizacao",
  case when v.vehicle_origin_code = 2 then 1 else 0 end  as "veiculoCedido",
  v.cession_destination_organ                            as "orgaoDestVeicCedido",
  v.cession_start_date                                   as "dataInicCessao",
  v.cession_end_date                                     as "dataFimCessao"
from vehicle v
cross join entity e
where v.deleted_at is null and v.vehicle_origin_code in (1,2);

-- 443 — Locados e Sublocados
create or replace view v_tce_443_locados as
select
  v.model                                       as "modelo",
  v.plate                                       as "placa",
  v.renavam                                     as "renavam",
  v.year_manufacture                            as "anoFabricacao",
  v.year_model                                  as "anoModelo",
  v.fuel_type_code                              as "tipoCombustivel",
  v.lessor_doc                                  as "cpfOuCnpj",
  v.lessor_name                                 as "nomeLocador",
  e.ibge_code                                   as "localizacao",
  v.monthly_value                               as "valorUnitMensal",
  case when v.has_driver then 1 else 0 end      as "possuiMotorista",
  v.cw_contract_code                            as "codigoCw"
from vehicle v
cross join entity e
where v.deleted_at is null and v.vehicle_origin_code in (3,4);

-- Saldo consolidado fornecedor × combustível
create or replace view v_supplier_balance as
select
  s.id           as supplier_id,
  s.trade_name,
  s.legal_name,
  s.cnpj,
  ft.code        as fuel_code,
  ft.description as fuel_description,
  sf.unit_price,
  sf.contract_amount,
  sf.current_balance,
  case when sf.contract_amount = 0 then null
       else sf.contract_amount - sf.current_balance end as used_amount,
  case when sf.contract_amount = 0 then null
       else round(sf.current_balance / sf.contract_amount * 100, 2) end as balance_percent
from supplier_fuel sf
join supplier s on s.id = sf.supplier_id
join fuel_type ft on ft.code = sf.fuel_type_code;

-- Uso mensal de autorizações por responsável (suporta painel de limite)
create or replace view v_monthly_authorization_usage as
select
  responsible_name,
  date_trunc('month', date)::date as ref_month,
  count(*)                        as auth_count,
  sum(estimated_total)            as total_value
from fueling_authorization
where status in ('emitida','utilizada') and deleted_at is null
group by responsible_name, date_trunc('month', date);

-- Agregado por veículo (relatório interno)
create or replace view v_report_by_vehicle as
select
  v.id,
  v.plate,
  v.model,
  d.acronym       as department_acronym,
  d.name          as department_name,
  vo.description  as origin,
  count(f.*)      as fueling_count,
  coalesce(sum(f.quantity),0)::numeric(12,2)              as total_liters,
  coalesce(sum(f.total),0)::numeric(14,2)                 as total_value,
  coalesce(sum(coalesce(f.km_final,0) - coalesce(f.km_initial,0)),0) as total_km,
  case when coalesce(sum(f.quantity),0) > 0
       then round(coalesce(sum(coalesce(f.km_final,0) - coalesce(f.km_initial,0)),0)::numeric
            / sum(f.quantity), 2)
       else null end as km_per_liter
from vehicle v
left join fueling f on f.vehicle_id = v.id and f.deleted_at is null
left join department d on d.id = v.department_id
left join vehicle_origin vo on vo.code = v.vehicle_origin_code
where v.deleted_at is null
group by v.id, v.plate, v.model, d.acronym, d.name, vo.description;

-- Agregado por secretaria
create or replace view v_report_by_department as
select
  d.id,
  d.acronym,
  d.name,
  count(f.*)                                  as fueling_count,
  coalesce(sum(f.quantity),0)::numeric(12,2)  as total_liters,
  coalesce(sum(f.total),0)::numeric(14,2)     as total_value
from department d
left join vehicle v on v.department_id = d.id and v.deleted_at is null
left join fueling f on f.vehicle_id = v.id and f.deleted_at is null
group by d.id, d.acronym, d.name;

-- Agregado por fornecedor
create or replace view v_report_by_supplier as
select
  s.id,
  s.trade_name,
  s.legal_name,
  s.cnpj,
  count(f.*)                                  as fueling_count,
  coalesce(sum(f.quantity),0)::numeric(12,2)  as total_liters,
  coalesce(sum(f.total),0)::numeric(14,2)     as total_invoiced
from supplier s
left join fueling f on f.supplier_id = s.id and f.deleted_at is null
group by s.id, s.trade_name, s.legal_name, s.cnpj;

-- =============================================================================
-- RLS
-- =============================================================================
alter table ibge_municipality      enable row level security;
alter table vehicle_type           enable row level security;
alter table fuel_type              enable row level security;
alter table fuel_subtype           enable row level security;
alter table vehicle_origin         enable row level security;
alter table sim_nao                enable row level security;
alter table entity                 enable row level security;
alter table app_user               enable row level security;
alter table department             enable row level security;
alter table vehicle                enable row level security;
alter table supplier               enable row level security;
alter table supplier_fuel          enable row level security;
alter table fueling_authorization  enable row level security;
alter table fueling                enable row level security;
alter table maintenance            enable row level security;

-- helpers
create or replace function current_user_role() returns user_role
language sql stable security definer set search_path = public as $$
  select role from app_user where id = auth.uid()
$$;

create or replace function current_user_supplier_id() returns uuid
language sql stable security definer set search_path = public as $$
  select supplier_id from app_user where id = auth.uid()
$$;

-- Lookups: leitura para qualquer autenticado
create policy p_ibge_read       on ibge_municipality for select using (auth.role() = 'authenticated');
create policy p_vehtype_read    on vehicle_type      for select using (auth.role() = 'authenticated');
create policy p_fueltype_read   on fuel_type         for select using (auth.role() = 'authenticated');
create policy p_fuelsubtype_read on fuel_subtype     for select using (auth.role() = 'authenticated');
create policy p_vehorigin_read  on vehicle_origin    for select using (auth.role() = 'authenticated');
create policy p_simnao_read     on sim_nao           for select using (auth.role() = 'authenticated');

-- Entity: read para todo autenticado; write só admin
create policy p_entity_read        on entity for select using (auth.role() = 'authenticated');
create policy p_entity_admin_write on entity for all
  using (current_user_role() = 'admin') with check (current_user_role() = 'admin');

-- App_user: cada um lê o próprio; admin lê e escreve todos
create policy p_appuser_self_read  on app_user for select
  using (id = auth.uid() or current_user_role() = 'admin');
create policy p_appuser_admin_all  on app_user for all
  using (current_user_role() = 'admin') with check (current_user_role() = 'admin');

-- Department: read autenticado; write admin
create policy p_dept_read        on department for select using (auth.role() = 'authenticated');
create policy p_dept_admin_write on department for all
  using (current_user_role() = 'admin') with check (current_user_role() = 'admin');

-- Vehicle: admin + usuario leem; admin escreve
create policy p_vehicle_read_internal on vehicle for select
  using (current_user_role() in ('admin','usuario'));
create policy p_vehicle_admin_write   on vehicle for all
  using (current_user_role() = 'admin') with check (current_user_role() = 'admin');

-- Supplier + supplier_fuel: admin/usuario leem geral; fornecedor lê só o próprio
create policy p_supplier_read_internal on supplier for select
  using (current_user_role() in ('admin','usuario'));
create policy p_supplier_read_self     on supplier for select
  using (current_user_role() = 'fornecedor' and id = current_user_supplier_id());
create policy p_supplier_admin_write   on supplier for all
  using (current_user_role() = 'admin') with check (current_user_role() = 'admin');

create policy p_supfuel_read_internal on supplier_fuel for select
  using (current_user_role() in ('admin','usuario'));
create policy p_supfuel_read_self     on supplier_fuel for select
  using (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());
create policy p_supfuel_admin_write   on supplier_fuel for all
  using (current_user_role() = 'admin') with check (current_user_role() = 'admin');

-- Authorization: admin+usuario tudo; fornecedor lê só do próprio supplier
create policy p_auth_read_internal on fueling_authorization for select
  using (current_user_role() in ('admin','usuario'));
create policy p_auth_read_self     on fueling_authorization for select
  using (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());
create policy p_auth_internal_write on fueling_authorization for all
  using (current_user_role() in ('admin','usuario'))
  with check (current_user_role() in ('admin','usuario'));

-- Fueling: admin+usuario tudo; fornecedor pode insert/update no próprio
create policy p_fueling_read_internal on fueling for select
  using (current_user_role() in ('admin','usuario'));
create policy p_fueling_read_self     on fueling for select
  using (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());
create policy p_fueling_internal_write on fueling for all
  using (current_user_role() in ('admin','usuario'))
  with check (current_user_role() in ('admin','usuario'));
create policy p_fueling_supplier_ins on fueling for insert
  with check (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());
create policy p_fueling_supplier_upd on fueling for update
  using (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());

-- Maintenance: admin + usuario
create policy p_maint_read  on maintenance for select
  using (current_user_role() in ('admin','usuario'));
create policy p_maint_write on maintenance for all
  using (current_user_role() in ('admin','usuario'))
  with check (current_user_role() in ('admin','usuario'));

-- =============================================================================
-- TRIGGER: garante que fuel_subtype_id pertence ao mesmo fuel_type_code da linha
-- =============================================================================
create or replace function ck_fuel_subtype_consistency() returns trigger
language plpgsql as $$
declare v_parent smallint;
begin
  if new.fuel_subtype_id is null then return new; end if;
  select fuel_type_code into v_parent from fuel_subtype where id = new.fuel_subtype_id;
  if v_parent is null then
    raise exception 'Subtipo de combustível % não existe', new.fuel_subtype_id using errcode = '23503';
  end if;
  if v_parent <> new.fuel_type_code then
    raise exception 'Subtipo % pertence ao combustível código %, mas a linha usa código %',
      new.fuel_subtype_id, v_parent, new.fuel_type_code using errcode = '23514';
  end if;
  return new;
end;
$$;
create trigger trg_supplier_fuel_subtype before insert or update on supplier_fuel
  for each row execute function ck_fuel_subtype_consistency();
create trigger trg_vehicle_subtype before insert or update on vehicle
  for each row execute function ck_fuel_subtype_consistency();
create trigger trg_auth_subtype before insert or update on fueling_authorization
  for each row execute function ck_fuel_subtype_consistency();
create trigger trg_fueling_subtype before insert or update on fueling
  for each row execute function ck_fuel_subtype_consistency();

-- =============================================================================
-- GRANTS — Supabase não dá grant automático em tabelas novas
-- =============================================================================
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on all functions in schema public to authenticated;

alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public
  grant usage, select on sequences to authenticated;
alter default privileges in schema public
  grant execute on functions to authenticated;

-- Anon (pré-login) precisa ler lookups e chamar email_from_username
grant select on ibge_municipality, vehicle_type, fuel_type, fuel_subtype, vehicle_origin, sim_nao to anon;
grant execute on function email_from_username(text) to anon;


-- =============================================================================
-- PATCHES CONSOLIDADOS (antigos apply.sql/patch.sql)
-- Tudo idempotente: pode rodar várias vezes sem efeito colateral.
-- Em instância nova: rodar este init.sql aplica TUDO de uma vez.
-- =============================================================================

-- =============================================================================
-- 1) GRANTs (sem isso Postgres bloqueia antes de a RLS rodar)
-- =============================================================================
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on all functions in schema public to authenticated;

alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public
  grant usage, select on sequences to authenticated;
alter default privileges in schema public
  grant execute on functions to authenticated;

grant select on
  ibge_municipality, vehicle_type, fuel_type, vehicle_origin, sim_nao
to anon;

grant execute on function email_from_username(text) to anon;

-- =============================================================================
-- 2) Funções admin (criar/excluir/redefinir senha de usuário sem Edge Function)
-- =============================================================================
create extension if not exists pgcrypto;

create or replace function _require_admin() returns void
language plpgsql security definer set search_path = public as $$
declare v_role user_role; v_active boolean;
begin
  select role, active into v_role, v_active from app_user where id = auth.uid();
  if v_role is null then raise exception 'Sessão inválida' using errcode = '28000'; end if;
  if v_role <> 'admin' or not v_active then
    raise exception 'Apenas administradores ativos podem executar esta ação' using errcode = '42501';
  end if;
end;
$$;
revoke all on function _require_admin() from public;
grant execute on function _require_admin() to authenticated;

create or replace function admin_create_user(
  p_email text, p_password text, p_username text, p_full_name text, p_role user_role,
  p_supplier_id uuid default null, p_access_start date default null,
  p_access_end date default null, p_monthly_authorization_limit numeric default 0
) returns uuid
language plpgsql security definer set search_path = public, auth as $$
declare v_user_id uuid := gen_random_uuid();
begin
  perform _require_admin();
  if p_email is null or position('@' in p_email) = 0 then raise exception 'Email inválido' using errcode = '22023'; end if;
  if p_password is null or length(p_password) < 6 then raise exception 'Senha deve ter ao menos 6 caracteres' using errcode = '22023'; end if;
  if p_username !~ '^[a-z0-9._-]{3,30}$' then raise exception 'Username inválido (3-30 chars, [a-z0-9._-])' using errcode = '22023'; end if;
  if exists (select 1 from app_user where username = p_username) then raise exception 'Username já em uso' using errcode = '23505'; end if;
  if exists (select 1 from auth.users where email = p_email) then raise exception 'Email já em uso' using errcode = '23505'; end if;
  if p_role = 'fornecedor' and p_supplier_id is null then raise exception 'Fornecedor exige supplier_id' using errcode = '22023'; end if;

  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
    confirmation_token, email_change, email_change_token_new, recovery_token
  ) values (
    '00000000-0000-0000-0000-000000000000', v_user_id, 'authenticated', 'authenticated',
    p_email, extensions.crypt(p_password, extensions.gen_salt('bf')), now(),
    jsonb_build_object('provider','email','providers',jsonb_build_array('email')),
    jsonb_build_object('full_name', p_full_name), now(), now(), '', '', '', ''
  );
  insert into auth.identities (
    id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
  ) values (
    gen_random_uuid(), v_user_id, v_user_id::text,
    jsonb_build_object('sub', v_user_id::text, 'email', p_email, 'email_verified', true),
    'email', now(), now(), now()
  );
  insert into app_user (
    id, username, full_name, role, supplier_id,
    access_start, access_end, monthly_authorization_limit, active
  ) values (
    v_user_id, p_username, p_full_name, p_role,
    case when p_role = 'fornecedor' then p_supplier_id else null end,
    p_access_start, p_access_end, coalesce(p_monthly_authorization_limit, 0), true
  );
  return v_user_id;
end;
$$;
revoke all on function admin_create_user(text,text,text,text,user_role,uuid,date,date,numeric) from public;
grant execute on function admin_create_user(text,text,text,text,user_role,uuid,date,date,numeric) to authenticated;

create or replace function admin_delete_user(p_user_id uuid) returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  perform _require_admin();
  if p_user_id = auth.uid() then raise exception 'Você não pode excluir o próprio usuário' using errcode = '42501'; end if;
  delete from auth.users where id = p_user_id;
  if not found then raise exception 'Usuário não encontrado' using errcode = '02000'; end if;
end;
$$;
revoke all on function admin_delete_user(uuid) from public;
grant execute on function admin_delete_user(uuid) to authenticated;

create or replace function admin_set_user_password(p_user_id uuid, p_new_password text) returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  perform _require_admin();
  if p_new_password is null or length(p_new_password) < 6 then
    raise exception 'Senha deve ter ao menos 6 caracteres' using errcode = '22023';
  end if;
  update auth.users
     set encrypted_password = extensions.crypt(p_new_password, extensions.gen_salt('bf')), updated_at = now()
   where id = p_user_id;
  if not found then raise exception 'Usuário não encontrado' using errcode = '02000'; end if;
end;
$$;
revoke all on function admin_set_user_password(uuid,text) from public;
grant execute on function admin_set_user_password(uuid,text) to authenticated;

drop function if exists admin_list_users();
create or replace function admin_list_users()
returns table (
  id uuid, username text, full_name text, role user_role, active boolean,
  supplier_id uuid, monthly_authorization_limit numeric,
  access_start date, access_end date, created_at timestamptz, email text
)
language plpgsql security definer set search_path = public, auth as $$
begin
  perform _require_admin();
  return query
    select au.id::uuid,
           au.username::text,
           au.full_name::text,
           au.role::user_role,
           au.active::boolean,
           au.supplier_id::uuid,
           au.monthly_authorization_limit::numeric,
           au.access_start::date,
           au.access_end::date,
           au.created_at::timestamptz,
           u.email::text
      from app_user au
      left join auth.users u on u.id = au.id
      order by au.created_at;
end;
$$;
revoke all on function admin_list_users() from public;
grant execute on function admin_list_users() to authenticated;

-- =============================================================================
-- 3) Migration v4 — datas de locação no veículo (cliente_v4.html)
-- TCE 443 não exige; uso interno pra filtrar exportações por vigência.
-- =============================================================================
alter table vehicle add column if not exists lessor_lease_start_date date;
alter table vehicle add column if not exists lessor_lease_end_date   date;

alter table vehicle drop constraint if exists chk_lease_dates;
alter table vehicle add  constraint chk_lease_dates check (
  lessor_lease_end_date is null
  or lessor_lease_start_date is null
  or lessor_lease_end_date >= lessor_lease_start_date
);

-- =============================================================================
-- 4) Migration v5 — fornecedor ganha secretaria de origem e nº de contrato
-- (cliente_v5.html). department_id nullable pra tolerar fornecedores legados.
-- contract_number texto livre (ex.: '012/2025'), sem CHECK de formato.
-- =============================================================================
alter table supplier add column if not exists department_id uuid references department(id);
alter table supplier add column if not exists contract_number text;

create index if not exists ix_supplier_department on supplier (department_id);

-- =============================================================================
-- 5) Migration v6 — subtipos comerciais de combustível
-- TCE-PI não conhece subtipos. Cada subtipo aponta pro fuel_type oficial
-- (ex.: "Diesel S10" → código 4 DIESEL). Exportações TCE continuam usando
-- só o pai (fuel_type_code). Subtipo serve apenas pra UX/relatórios internos.
-- =============================================================================

create table if not exists fuel_subtype (
  id smallint primary key generated by default as identity,
  fuel_type_code smallint not null references fuel_type(code),
  description text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists ix_fuel_subtype_parent on fuel_subtype (fuel_type_code) where active;

-- (Seed de fuel_subtype foi movido pro dump.sql — depende de fuel_type estar
-- populada, o que só acontece após init.sql rodar.)

-- Coluna opcional fuel_subtype_id em todas as tabelas que usam combustível
alter table supplier_fuel          add column if not exists fuel_subtype_id smallint references fuel_subtype(id);
alter table vehicle                add column if not exists fuel_subtype_id smallint references fuel_subtype(id);
alter table fueling_authorization  add column if not exists fuel_subtype_id smallint references fuel_subtype(id);
alter table fueling                add column if not exists fuel_subtype_id smallint references fuel_subtype(id);

-- Unicidade do supplier_fuel passa a considerar subtype
-- (COALESCE pra tratar NULL como valor real e evitar duplicatas implícitas)
alter table supplier_fuel drop constraint if exists supplier_fuel_supplier_id_fuel_type_code_key;
drop index if exists ux_supplier_fuel_unique;
create unique index ux_supplier_fuel_unique
  on supplier_fuel (supplier_id, fuel_type_code, coalesce(fuel_subtype_id, 0::smallint));

-- Trigger: subtype deve pertencer ao mesmo fuel_type_code da linha
create or replace function ck_fuel_subtype_consistency() returns trigger
language plpgsql as $$
declare v_parent smallint;
begin
  if new.fuel_subtype_id is null then return new; end if;
  select fuel_type_code into v_parent from fuel_subtype where id = new.fuel_subtype_id;
  if v_parent is null then
    raise exception 'Subtipo de combustível % não existe', new.fuel_subtype_id using errcode = '23503';
  end if;
  if v_parent <> new.fuel_type_code then
    raise exception 'Subtipo % pertence ao combustível código %, mas a linha usa código %',
      new.fuel_subtype_id, v_parent, new.fuel_type_code using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_supplier_fuel_subtype on supplier_fuel;
create trigger trg_supplier_fuel_subtype before insert or update on supplier_fuel
  for each row execute function ck_fuel_subtype_consistency();

drop trigger if exists trg_vehicle_subtype on vehicle;
create trigger trg_vehicle_subtype before insert or update on vehicle
  for each row execute function ck_fuel_subtype_consistency();

drop trigger if exists trg_auth_subtype on fueling_authorization;
create trigger trg_auth_subtype before insert or update on fueling_authorization
  for each row execute function ck_fuel_subtype_consistency();

drop trigger if exists trg_fueling_subtype on fueling;
create trigger trg_fueling_subtype before insert or update on fueling
  for each row execute function ck_fuel_subtype_consistency();

-- RLS + GRANTs (mesma política das outras lookups: leitura pra qualquer autenticado/anon)
alter table fuel_subtype enable row level security;
drop policy if exists p_fuelsubtype_read on fuel_subtype;
create policy p_fuelsubtype_read on fuel_subtype for select using (auth.role() in ('anon','authenticated'));
grant select on fuel_subtype to anon, authenticated;

-- =============================================================================
-- 6) RPCs de autorização — versão v7 com suporte a fuel_subtype
-- emit/cancel/update_qty agora consideram subtipo ao debitar/restaurar saldo,
-- e há delete_authorization que restaura saldo se a aut. estiver emitida.
-- QR payload virou um texto rico, multi-linha, fácil de ler ao escanear.
-- =============================================================================

drop function if exists emit_authorization(date,uuid,uuid,smallint,numeric,text,text);
drop function if exists emit_authorization(date,uuid,uuid,smallint,numeric,text,text,smallint);

create or replace function emit_authorization(
  p_date date,
  p_vehicle_id uuid,
  p_supplier_id uuid,
  p_fuel_type_code smallint,
  p_quantity numeric,
  p_responsible_name text,
  p_notes text default null,
  p_fuel_subtype_id smallint default null
) returns uuid
language plpgsql security definer set search_path = public, auth as $$
declare
  v_auth_id uuid;
  v_number  text;
  v_price   numeric(8,3);
  v_contract numeric; v_balance numeric;
  v_tank    numeric;
  v_user_limit numeric; v_month_used numeric; v_estimated numeric;
  v_plate text; v_model text; v_dept text; v_sup_name text; v_sup_cnpj text; v_qr text;
  v_fuel_desc text; v_sub_desc text;
begin
  -- Snapshots do veículo
  select plate, model, tank_capacity into v_plate, v_model, v_tank
    from vehicle where id = p_vehicle_id and deleted_at is null;
  if v_plate is null then raise exception 'Veículo não encontrado'; end if;

  select d.acronym into v_dept
    from vehicle v left join department d on d.id = v.department_id
    where v.id = p_vehicle_id;

  select coalesce(trade_name, legal_name), cnpj
    into v_sup_name, v_sup_cnpj
    from supplier where id = p_supplier_id;
  if v_sup_name is null then raise exception 'Fornecedor não encontrado'; end if;

  if v_tank is not null and p_quantity > v_tank then
    raise exception 'Quantidade % L excede capacidade do tanque (% L)', p_quantity, v_tank;
  end if;

  -- Descrição do subtipo (se houver)
  if p_fuel_subtype_id is not null then
    select description into v_sub_desc from fuel_subtype where id = p_fuel_subtype_id;
    if v_sub_desc is null then
      raise exception 'Subtipo de combustível % não existe', p_fuel_subtype_id;
    end if;
  end if;

  -- Preço, saldo: busca pela combinação supplier × fuel_type × subtype
  select unit_price, contract_amount, current_balance
    into v_price, v_contract, v_balance
    from supplier_fuel
    where supplier_id = p_supplier_id
      and fuel_type_code = p_fuel_type_code
      and coalesce(fuel_subtype_id, 0::smallint) = coalesce(p_fuel_subtype_id, 0::smallint);
  if v_price is null then
    raise exception 'Fornecedor não vende esse combustível%',
      case when p_fuel_subtype_id is not null then ' (' || v_sub_desc || ')' else '' end;
  end if;
  if v_contract > 0 and p_quantity > v_balance then
    raise exception 'Saldo insuficiente: disponível % L, solicitado % L', v_balance, p_quantity;
  end if;
  v_estimated := p_quantity * v_price;

  -- Limite mensal do responsável
  select monthly_authorization_limit into v_user_limit
    from app_user
    where full_name = p_responsible_name and active = true
    limit 1;
  if v_user_limit is not null and v_user_limit > 0 then
    select coalesce(sum(estimated_total),0) into v_month_used
      from fueling_authorization
      where responsible_name = p_responsible_name
        and status in ('emitida','utilizada')
        and date_trunc('month', date) = date_trunc('month', p_date)
        and deleted_at is null;
    if v_month_used + v_estimated > v_user_limit then
      raise exception 'Limite mensal do responsável excedido: limite R$%, usado R$%, nova R$%',
        v_user_limit, v_month_used, v_estimated;
    end if;
  end if;

  -- Número da autorização + payload do QR (texto rico, escaneável)
  v_number := generate_authorization_number(p_date);
  select description into v_fuel_desc from fuel_type where code = p_fuel_type_code;

  v_qr := format(
    E'GERIR FROTA — AUTORIZAÇÃO DE ABASTECIMENTO\n' ||
    E'Nº: %s\n' ||
    E'Data: %s\n' ||
    E'Veículo: %s — %s\n' ||
    E'Combustível: %s%s\n' ||
    E'Quantidade: %s L\n' ||
    E'Valor estimado: R$ %s\n' ||
    E'Fornecedor: %s (CNPJ %s)\n' ||
    E'Secretaria: %s\n' ||
    E'Responsável: %s\n' ||
    E'Situação: EMITIDA',
    v_number,
    to_char(p_date,'DD/MM/YYYY'),
    v_plate, v_model,
    v_fuel_desc,
    case when v_sub_desc is not null then ' / ' || v_sub_desc else '' end,
    to_char(p_quantity, 'FM999990D90'),
    to_char(v_estimated, 'FM999990D90'),
    v_sup_name, v_sup_cnpj,
    coalesce(v_dept, '—'),
    p_responsible_name
  );

  insert into fueling_authorization (
    number, date, vehicle_id, supplier_id, fuel_type_code, fuel_subtype_id,
    authorized_quantity, unit_price_snapshot, responsible_name, notes,
    vehicle_plate_snapshot, vehicle_model_snapshot,
    department_acronym_snapshot, supplier_trade_name_snapshot,
    qr_payload, created_by
  ) values (
    v_number, p_date, p_vehicle_id, p_supplier_id, p_fuel_type_code, p_fuel_subtype_id,
    p_quantity, v_price, p_responsible_name, p_notes,
    v_plate, v_model, v_dept, v_sup_name,
    v_qr, auth.uid()
  ) returning id into v_auth_id;

  -- Debita saldo
  if v_contract > 0 then
    update supplier_fuel
      set current_balance = current_balance - p_quantity
      where supplier_id = p_supplier_id
        and fuel_type_code = p_fuel_type_code
        and coalesce(fuel_subtype_id, 0::smallint) = coalesce(p_fuel_subtype_id, 0::smallint);
  end if;

  return v_auth_id;
end;
$$;
revoke all on function emit_authorization(date,uuid,uuid,smallint,numeric,text,text,smallint) from public;
grant execute on function emit_authorization(date,uuid,uuid,smallint,numeric,text,text,smallint) to authenticated;


create or replace function cancel_authorization(p_auth_id uuid) returns void
language plpgsql security definer set search_path = public, auth as $$
declare v_sup uuid; v_fuel smallint; v_subtype smallint; v_qty numeric; v_contract numeric;
begin
  select supplier_id, fuel_type_code, fuel_subtype_id, authorized_quantity
    into v_sup, v_fuel, v_subtype, v_qty
    from fueling_authorization
    where id = p_auth_id and status = 'emitida' and deleted_at is null;
  if v_sup is null then raise exception 'Autorização não encontrada ou não está emitida'; end if;

  update fueling_authorization set status = 'cancelada' where id = p_auth_id;

  select contract_amount into v_contract from supplier_fuel
    where supplier_id = v_sup
      and fuel_type_code = v_fuel
      and coalesce(fuel_subtype_id, 0::smallint) = coalesce(v_subtype, 0::smallint);
  if v_contract > 0 then
    update supplier_fuel
      set current_balance = least(contract_amount, current_balance + v_qty)
      where supplier_id = v_sup
        and fuel_type_code = v_fuel
        and coalesce(fuel_subtype_id, 0::smallint) = coalesce(v_subtype, 0::smallint);
  end if;
end;
$$;


create or replace function update_authorization_quantity(p_auth_id uuid, p_new_qty numeric) returns void
language plpgsql security definer set search_path = public, auth as $$
declare
  v_sup uuid; v_fuel smallint; v_subtype smallint;
  v_old numeric; v_unit_price numeric; v_contract numeric; v_balance numeric; v_diff numeric;
begin
  if p_new_qty <= 0 then raise exception 'Quantidade deve ser > 0'; end if;

  select supplier_id, fuel_type_code, fuel_subtype_id, authorized_quantity, unit_price_snapshot
    into v_sup, v_fuel, v_subtype, v_old, v_unit_price
    from fueling_authorization
    where id = p_auth_id and status = 'emitida' and deleted_at is null;
  if v_sup is null then raise exception 'Autorização não encontrada ou não está emitida'; end if;

  v_diff := p_new_qty - v_old;
  if v_diff = 0 then return; end if;

  select contract_amount, current_balance into v_contract, v_balance
    from supplier_fuel
    where supplier_id = v_sup
      and fuel_type_code = v_fuel
      and coalesce(fuel_subtype_id, 0::smallint) = coalesce(v_subtype, 0::smallint);

  if v_contract > 0 and v_diff > 0 and v_diff > v_balance then
    raise exception 'Saldo insuficiente para aumento: disponível % L', v_balance;
  end if;

  update fueling_authorization
    set authorized_quantity = p_new_qty
    where id = p_auth_id;

  if v_contract > 0 then
    update supplier_fuel
      set current_balance = least(contract_amount, current_balance - v_diff)
      where supplier_id = v_sup
        and fuel_type_code = v_fuel
        and coalesce(fuel_subtype_id, 0::smallint) = coalesce(v_subtype, 0::smallint);
  end if;
end;
$$;


create or replace function delete_authorization(p_auth_id uuid) returns void
language plpgsql security definer set search_path = public, auth as $$
declare
  v_status authorization_status; v_sup uuid; v_fuel smallint; v_subtype smallint;
  v_qty numeric; v_contract numeric; v_used_count integer;
begin
  select status, supplier_id, fuel_type_code, fuel_subtype_id, authorized_quantity
    into v_status, v_sup, v_fuel, v_subtype, v_qty
    from fueling_authorization
    where id = p_auth_id and deleted_at is null;
  if v_status is null then raise exception 'Autorização não encontrada'; end if;

  -- Bloqueia delete se há abastecimentos vinculados
  select count(*) into v_used_count from fueling
    where authorization_id = p_auth_id and deleted_at is null;
  if v_used_count > 0 then
    raise exception 'Não é possível excluir: % abastecimento(s) vinculado(s) a esta autorização.', v_used_count;
  end if;

  -- Se ainda emitida, restaura saldo antes de deletar
  if v_status = 'emitida' then
    select contract_amount into v_contract from supplier_fuel
      where supplier_id = v_sup
        and fuel_type_code = v_fuel
        and coalesce(fuel_subtype_id, 0::smallint) = coalesce(v_subtype, 0::smallint);
    if v_contract > 0 then
      update supplier_fuel
        set current_balance = least(contract_amount, current_balance + v_qty)
        where supplier_id = v_sup
          and fuel_type_code = v_fuel
          and coalesce(fuel_subtype_id, 0::smallint) = coalesce(v_subtype, 0::smallint);
    end if;
  end if;

  delete from fueling_authorization where id = p_auth_id;
end;
$$;
revoke all on function delete_authorization(uuid) from public;
grant execute on function delete_authorization(uuid) to authenticated;

-- =============================================================================
-- 7) Autorização de manutenção (mecânica) — tabela separada e RPCs
-- Mecânica recebe autorização sem litros: tem serviço descrito e valor estimado.
-- Numeração: 'AAAAMMDD-MAN-NNN' (série independente das de combustível).
-- Limite mensal do responsável passa a somar combustível + manutenção.
-- =============================================================================

do $$ begin
  if not exists (select 1 from pg_type where typname = 'service_kind') then
    create type service_kind as enum ('preventiva','corretiva','sinistro','revisao','outros');
  end if;
end $$;

create table if not exists service_authorization (
  id uuid primary key default gen_random_uuid(),
  number text not null unique,                          -- 'AAAAMMDD-MAN-NNN'
  date date not null,
  status authorization_status not null default 'emitida',
  vehicle_id uuid not null references vehicle(id),
  supplier_id uuid not null references supplier(id),
  service_kind service_kind not null default 'corretiva',
  description text not null,
  estimated_value numeric(12,2) not null check (estimated_value > 0),
  responsible_name text not null,
  notes text,
  -- snapshots
  vehicle_plate_snapshot text not null,
  vehicle_model_snapshot text not null,
  department_acronym_snapshot text,
  supplier_trade_name_snapshot text not null,
  qr_payload text not null,
  created_by uuid references app_user(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists ix_serv_auth_date on service_authorization (date);
create index if not exists ix_serv_auth_status on service_authorization (status) where deleted_at is null;
create index if not exists ix_serv_auth_vehicle on service_authorization (vehicle_id);
create index if not exists ix_serv_auth_supplier on service_authorization (supplier_id);
create index if not exists ix_serv_auth_resp on service_authorization (responsible_name);

drop trigger if exists trg_service_auth_set_updated_at on service_authorization;
create trigger trg_service_auth_set_updated_at before update on service_authorization
  for each row execute function set_updated_at();

-- RLS espelhando fueling_authorization
alter table service_authorization enable row level security;
drop policy if exists p_servauth_read_internal on service_authorization;
create policy p_servauth_read_internal on service_authorization for select
  using (current_user_role() in ('admin','usuario'));
drop policy if exists p_servauth_read_self on service_authorization;
create policy p_servauth_read_self on service_authorization for select
  using (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());
drop policy if exists p_servauth_internal_write on service_authorization;
create policy p_servauth_internal_write on service_authorization for all
  using (current_user_role() in ('admin','usuario'))
  with check (current_user_role() in ('admin','usuario'));

-- ===== RPCs =====

create or replace function generate_service_authorization_number(p_date date) returns text
language plpgsql as $$
declare ds text; n int;
begin
  ds := to_char(p_date,'YYYYMMDD');
  select count(*)+1 into n from service_authorization where number like ds || '-MAN-%';
  return ds || '-MAN-' || lpad(n::text,3,'0');
end;
$$;

create or replace function emit_service_authorization(
  p_date date,
  p_vehicle_id uuid,
  p_supplier_id uuid,
  p_service_kind service_kind,
  p_description text,
  p_estimated_value numeric,
  p_responsible_name text,
  p_notes text default null
) returns uuid
language plpgsql security definer set search_path = public, auth as $$
declare
  v_auth_id uuid; v_number text;
  v_plate text; v_model text; v_dept text; v_sup_name text; v_sup_cnpj text; v_sup_kind supplier_kind;
  v_user_limit numeric; v_month_used numeric;
  v_qr text;
begin
  -- Snapshots
  select plate, model into v_plate, v_model
    from vehicle where id = p_vehicle_id and deleted_at is null;
  if v_plate is null then raise exception 'Veículo não encontrado'; end if;
  select d.acronym into v_dept
    from vehicle v left join department d on d.id = v.department_id
    where v.id = p_vehicle_id;
  select kind, coalesce(trade_name, legal_name), cnpj
    into v_sup_kind, v_sup_name, v_sup_cnpj
    from supplier where id = p_supplier_id;
  if v_sup_name is null then raise exception 'Fornecedor não encontrado'; end if;
  if v_sup_kind = 'posto' then
    raise exception 'Fornecedor cadastrado apenas como Posto não pode receber autorização de manutenção';
  end if;
  if p_estimated_value is null or p_estimated_value <= 0 then
    raise exception 'Valor estimado deve ser maior que zero';
  end if;
  if p_description is null or length(trim(p_description)) < 3 then
    raise exception 'Descrição do serviço é obrigatória (mínimo 3 caracteres)';
  end if;

  -- Limite mensal (soma combustível + manutenção)
  select monthly_authorization_limit into v_user_limit
    from app_user
    where full_name = p_responsible_name and active = true
    limit 1;
  if v_user_limit is not null and v_user_limit > 0 then
    select coalesce((
      select sum(estimated_total) from fueling_authorization
       where responsible_name = p_responsible_name
         and status in ('emitida','utilizada')
         and date_trunc('month', date) = date_trunc('month', p_date)
         and deleted_at is null
    ), 0) + coalesce((
      select sum(estimated_value) from service_authorization
       where responsible_name = p_responsible_name
         and status in ('emitida','utilizada')
         and date_trunc('month', date) = date_trunc('month', p_date)
         and deleted_at is null
    ), 0)
    into v_month_used;
    if v_month_used + p_estimated_value > v_user_limit then
      raise exception 'Limite mensal do responsável excedido: limite R$%, usado R$%, nova R$%',
        v_user_limit, v_month_used, p_estimated_value;
    end if;
  end if;

  v_number := generate_service_authorization_number(p_date);
  v_qr := format(
    E'GERIR FROTA — AUTORIZAÇÃO DE MANUTENÇÃO\n' ||
    E'Nº: %s\n' ||
    E'Data: %s\n' ||
    E'Veículo: %s — %s\n' ||
    E'Categoria: %s\n' ||
    E'Serviço: %s\n' ||
    E'Valor estimado: R$ %s\n' ||
    E'Mecânica: %s (CNPJ %s)\n' ||
    E'Secretaria: %s\n' ||
    E'Responsável: %s\n' ||
    E'Situação: EMITIDA',
    v_number,
    to_char(p_date,'DD/MM/YYYY'),
    v_plate, v_model,
    upper(p_service_kind::text),
    p_description,
    to_char(p_estimated_value, 'FM999990D90'),
    v_sup_name, v_sup_cnpj,
    coalesce(v_dept,'—'),
    p_responsible_name
  );

  insert into service_authorization (
    number, date, vehicle_id, supplier_id, service_kind, description,
    estimated_value, responsible_name, notes,
    vehicle_plate_snapshot, vehicle_model_snapshot,
    department_acronym_snapshot, supplier_trade_name_snapshot,
    qr_payload, created_by
  ) values (
    v_number, p_date, p_vehicle_id, p_supplier_id, p_service_kind, p_description,
    p_estimated_value, p_responsible_name, p_notes,
    v_plate, v_model, v_dept, v_sup_name,
    v_qr, auth.uid()
  ) returning id into v_auth_id;
  return v_auth_id;
end;
$$;
revoke all on function emit_service_authorization(date,uuid,uuid,service_kind,text,numeric,text,text) from public;
grant execute on function emit_service_authorization(date,uuid,uuid,service_kind,text,numeric,text,text) to authenticated;


create or replace function cancel_service_authorization(p_auth_id uuid) returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  update service_authorization set status = 'cancelada'
   where id = p_auth_id and status = 'emitida' and deleted_at is null;
  if not found then raise exception 'Autorização de manutenção não encontrada ou não está emitida'; end if;
end;
$$;
revoke all on function cancel_service_authorization(uuid) from public;
grant execute on function cancel_service_authorization(uuid) to authenticated;


create or replace function update_service_authorization(
  p_auth_id uuid,
  p_service_kind service_kind,
  p_description text,
  p_estimated_value numeric,
  p_notes text default null
) returns void
language plpgsql security definer set search_path = public, auth as $$
declare v_status authorization_status;
begin
  if p_estimated_value <= 0 then raise exception 'Valor estimado deve ser > 0'; end if;
  if length(trim(coalesce(p_description, ''))) < 3 then raise exception 'Descrição do serviço obrigatória'; end if;
  select status into v_status from service_authorization where id = p_auth_id and deleted_at is null;
  if v_status is null then raise exception 'Autorização não encontrada'; end if;
  if v_status <> 'emitida' then raise exception 'Apenas autorizações emitidas podem ser editadas'; end if;
  update service_authorization
     set service_kind = p_service_kind,
         description = p_description,
         estimated_value = p_estimated_value,
         notes = p_notes
   where id = p_auth_id;
end;
$$;
revoke all on function update_service_authorization(uuid,service_kind,text,numeric,text) from public;
grant execute on function update_service_authorization(uuid,service_kind,text,numeric,text) to authenticated;


create or replace function delete_service_authorization(p_auth_id uuid) returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  delete from service_authorization where id = p_auth_id;
  if not found then raise exception 'Autorização não encontrada'; end if;
end;
$$;
revoke all on function delete_service_authorization(uuid) from public;
grant execute on function delete_service_authorization(uuid) to authenticated;

-- =============================================================================
-- 7.1) Atualiza emit_authorization (combustível) pra somar manutenção no limite
-- =============================================================================
drop function if exists emit_authorization(date,uuid,uuid,smallint,numeric,text,text,smallint);

create or replace function emit_authorization(
  p_date date,
  p_vehicle_id uuid,
  p_supplier_id uuid,
  p_fuel_type_code smallint,
  p_quantity numeric,
  p_responsible_name text,
  p_notes text default null,
  p_fuel_subtype_id smallint default null
) returns uuid
language plpgsql security definer set search_path = public, auth as $$
declare
  v_auth_id uuid; v_number text;
  v_price numeric(8,3); v_contract numeric; v_balance numeric;
  v_tank numeric;
  v_user_limit numeric; v_month_used numeric; v_estimated numeric;
  v_plate text; v_model text; v_dept text; v_sup_name text; v_sup_cnpj text; v_qr text;
  v_fuel_desc text; v_sub_desc text;
begin
  select plate, model, tank_capacity into v_plate, v_model, v_tank
    from vehicle where id = p_vehicle_id and deleted_at is null;
  if v_plate is null then raise exception 'Veículo não encontrado'; end if;
  select d.acronym into v_dept
    from vehicle v left join department d on d.id = v.department_id
    where v.id = p_vehicle_id;
  select coalesce(trade_name, legal_name), cnpj into v_sup_name, v_sup_cnpj
    from supplier where id = p_supplier_id;
  if v_sup_name is null then raise exception 'Fornecedor não encontrado'; end if;
  if v_tank is not null and p_quantity > v_tank then
    raise exception 'Quantidade % L excede capacidade do tanque (% L)', p_quantity, v_tank;
  end if;
  if p_fuel_subtype_id is not null then
    select description into v_sub_desc from fuel_subtype where id = p_fuel_subtype_id;
    if v_sub_desc is null then raise exception 'Subtipo de combustível % não existe', p_fuel_subtype_id; end if;
  end if;
  select unit_price, contract_amount, current_balance
    into v_price, v_contract, v_balance
    from supplier_fuel
    where supplier_id = p_supplier_id
      and fuel_type_code = p_fuel_type_code
      and coalesce(fuel_subtype_id, 0::smallint) = coalesce(p_fuel_subtype_id, 0::smallint);
  if v_price is null then
    raise exception 'Fornecedor não vende esse combustível%',
      case when p_fuel_subtype_id is not null then ' (' || v_sub_desc || ')' else '' end;
  end if;
  if v_contract > 0 and p_quantity > v_balance then
    raise exception 'Saldo insuficiente: disponível % L, solicitado % L', v_balance, p_quantity;
  end if;
  v_estimated := p_quantity * v_price;

  -- Limite mensal: soma combustível + manutenção
  select monthly_authorization_limit into v_user_limit
    from app_user where full_name = p_responsible_name and active = true limit 1;
  if v_user_limit is not null and v_user_limit > 0 then
    select coalesce((
      select sum(estimated_total) from fueling_authorization
       where responsible_name = p_responsible_name
         and status in ('emitida','utilizada')
         and date_trunc('month', date) = date_trunc('month', p_date)
         and deleted_at is null
    ), 0) + coalesce((
      select sum(estimated_value) from service_authorization
       where responsible_name = p_responsible_name
         and status in ('emitida','utilizada')
         and date_trunc('month', date) = date_trunc('month', p_date)
         and deleted_at is null
    ), 0)
    into v_month_used;
    if v_month_used + v_estimated > v_user_limit then
      raise exception 'Limite mensal do responsável excedido: limite R$%, usado R$%, nova R$%',
        v_user_limit, v_month_used, v_estimated;
    end if;
  end if;

  v_number := generate_authorization_number(p_date);
  select description into v_fuel_desc from fuel_type where code = p_fuel_type_code;
  v_qr := format(
    E'GERIR FROTA — AUTORIZAÇÃO DE ABASTECIMENTO\n' ||
    E'Nº: %s\nData: %s\nVeículo: %s — %s\nCombustível: %s%s\n' ||
    E'Quantidade: %s L\nValor estimado: R$ %s\n' ||
    E'Fornecedor: %s (CNPJ %s)\nSecretaria: %s\nResponsável: %s\nSituação: EMITIDA',
    v_number, to_char(p_date,'DD/MM/YYYY'), v_plate, v_model,
    v_fuel_desc, case when v_sub_desc is not null then ' / ' || v_sub_desc else '' end,
    to_char(p_quantity,'FM999990D90'), to_char(v_estimated,'FM999990D90'),
    v_sup_name, v_sup_cnpj, coalesce(v_dept,'—'), p_responsible_name
  );
  insert into fueling_authorization (
    number, date, vehicle_id, supplier_id, fuel_type_code, fuel_subtype_id,
    authorized_quantity, unit_price_snapshot, responsible_name, notes,
    vehicle_plate_snapshot, vehicle_model_snapshot,
    department_acronym_snapshot, supplier_trade_name_snapshot, qr_payload, created_by
  ) values (
    v_number, p_date, p_vehicle_id, p_supplier_id, p_fuel_type_code, p_fuel_subtype_id,
    p_quantity, v_price, p_responsible_name, p_notes,
    v_plate, v_model, v_dept, v_sup_name, v_qr, auth.uid()
  ) returning id into v_auth_id;
  if v_contract > 0 then
    update supplier_fuel
      set current_balance = current_balance - p_quantity
      where supplier_id = p_supplier_id
        and fuel_type_code = p_fuel_type_code
        and coalesce(fuel_subtype_id, 0::smallint) = coalesce(p_fuel_subtype_id, 0::smallint);
  end if;
  return v_auth_id;
end;
$$;
revoke all on function emit_authorization(date,uuid,uuid,smallint,numeric,text,text,smallint) from public;
grant execute on function emit_authorization(date,uuid,uuid,smallint,numeric,text,text,smallint) to authenticated;

-- =============================================================================
-- 8) Manutenção vinculada à autorização de manutenção
-- =============================================================================
alter table maintenance add column if not exists authorization_id uuid references service_authorization(id);
create index if not exists ix_maintenance_auth on maintenance (authorization_id);

create or replace function mark_service_authorization_as_used() returns trigger
language plpgsql as $$
begin
  if new.authorization_id is not null then
    update service_authorization
      set status = 'utilizada'
      where id = new.authorization_id and status = 'emitida';
  end if;
  return new;
end;
$$;
drop trigger if exists trg_maintenance_mark_auth_used on maintenance;
create trigger trg_maintenance_mark_auth_used after insert on maintenance
  for each row execute function mark_service_authorization_as_used();

create or replace function revert_service_authorization_on_maintenance_delete() returns trigger
language plpgsql as $$
declare n integer;
begin
  if old.authorization_id is null then return old; end if;
  select count(*) into n from maintenance
    where authorization_id = old.authorization_id
      and id <> old.id and deleted_at is null;
  if n = 0 then
    update service_authorization
      set status = 'emitida'
      where id = old.authorization_id and status = 'utilizada';
  end if;
  return old;
end;
$$;
drop trigger if exists trg_maintenance_revert_auth on maintenance;
create trigger trg_maintenance_revert_auth before delete on maintenance
  for each row execute function revert_service_authorization_on_maintenance_delete();

-- =============================================================================
-- 9) RLS: usuário 'usuario' vê só suas próprias autorizações (combustível e
-- manutenção). Admin continua vendo tudo. Fornecedor continua vendo só as do
-- supplier dele. Cliente pediu pra usuários comuns não verem autorizações de
-- outros responsáveis.
-- =============================================================================
drop policy if exists p_auth_read_internal on fueling_authorization;
create policy p_auth_read_internal on fueling_authorization for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario' and created_by = auth.uid())
  );

drop policy if exists p_servauth_read_internal on service_authorization;
create policy p_servauth_read_internal on service_authorization for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario' and created_by = auth.uid())
  );

-- =============================================================================
-- 10) RLS — fornecedor pode ler e concluir manutenções vinculadas ao próprio
-- supplier_id (paralelo ao que fueling já tem).
-- =============================================================================
drop policy if exists p_maint_read_self on maintenance;
create policy p_maint_read_self on maintenance for select
  using (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());

drop policy if exists p_maint_supplier_ins on maintenance;
create policy p_maint_supplier_ins on maintenance for insert
  with check (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());

drop policy if exists p_maint_supplier_upd on maintenance;
create policy p_maint_supplier_upd on maintenance for update
  using (current_user_role() = 'fornecedor' and supplier_id = current_user_supplier_id());

-- =============================================================================
-- 11) Vinculação usuário ↔ secretaria + RLS por secretaria
-- - app_user.department_id (1 user → 1 secretaria opcional)
-- - department.responsible_user_id (1 secretaria → 1 responsável)
-- - admin_set_department_responsible() sincroniza ambos lados
-- - usuario com department_id setado vê só dados da sua secretaria
--   (sem department_id = vê tudo, mantém compat com legado)
-- =============================================================================
alter table app_user   add column if not exists department_id      uuid references department(id) on delete set null;
alter table department add column if not exists responsible_user_id uuid references app_user(id)  on delete set null;
create index if not exists ix_appuser_department on app_user (department_id) where department_id is not null;
create index if not exists ix_department_responsible on department (responsible_user_id) where responsible_user_id is not null;

create or replace function current_user_department_id() returns uuid
language sql stable security definer set search_path = public as $$
  select department_id from app_user where id = auth.uid()
$$;
revoke all on function current_user_department_id() from public;
grant execute on function current_user_department_id() to authenticated;

create or replace function admin_set_department_responsible(
  p_dept_id uuid,
  p_user_id uuid
) returns void
language plpgsql security definer set search_path = public as $$
declare v_old_user uuid;
begin
  perform _require_admin();
  select responsible_user_id into v_old_user from department where id = p_dept_id;
  if v_old_user is not null and v_old_user is distinct from p_user_id then
    update app_user set department_id = null where id = v_old_user and department_id = p_dept_id;
  end if;
  update department set responsible_user_id = p_user_id where id = p_dept_id;
  if not found then raise exception 'Secretaria não encontrada'; end if;
  if p_user_id is not null then
    update app_user set department_id = p_dept_id where id = p_user_id;
  end if;
end;
$$;
revoke all on function admin_set_department_responsible(uuid,uuid) from public;
grant execute on function admin_set_department_responsible(uuid,uuid) to authenticated;

drop policy if exists p_vehicle_read_internal on vehicle;
create policy p_vehicle_read_internal on vehicle for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario'
        and (current_user_department_id() is null
             or department_id is null
             or department_id = current_user_department_id()))
  );

drop policy if exists p_fueling_read_internal on fueling;
create policy p_fueling_read_internal on fueling for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario'
        and (current_user_department_id() is null
             or exists (
               select 1 from vehicle v
                where v.id = fueling.vehicle_id
                  and (v.department_id is null
                       or v.department_id = current_user_department_id())
             )))
  );

drop policy if exists p_maint_read on maintenance;
create policy p_maint_read on maintenance for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario'
        and (current_user_department_id() is null
             or exists (
               select 1 from vehicle v
                where v.id = maintenance.vehicle_id
                  and (v.department_id is null
                       or v.department_id = current_user_department_id())
             )))
  );

drop policy if exists p_supplier_read_internal on supplier;
create policy p_supplier_read_internal on supplier for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario'
        and (current_user_department_id() is null
             or department_id is null
             or department_id = current_user_department_id()))
  );

drop policy if exists p_supfuel_read_internal on supplier_fuel;
create policy p_supfuel_read_internal on supplier_fuel for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario'
        and (current_user_department_id() is null
             or exists (
               select 1 from supplier s
                where s.id = supplier_fuel.supplier_id
                  and (s.department_id is null
                       or s.department_id = current_user_department_id())
             )))
  );

drop policy if exists p_auth_read_internal on fueling_authorization;
create policy p_auth_read_internal on fueling_authorization for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario'
        and (current_user_department_id() is null
             or exists (
               select 1 from vehicle v
                where v.id = fueling_authorization.vehicle_id
                  and (v.department_id is null
                       or v.department_id = current_user_department_id())
             )))
  );

drop policy if exists p_servauth_read_internal on service_authorization;
create policy p_servauth_read_internal on service_authorization for select
  using (
    current_user_role() = 'admin'
    or (current_user_role() = 'usuario'
        and (current_user_department_id() is null
             or exists (
               select 1 from vehicle v
                where v.id = service_authorization.vehicle_id
                  and (v.department_id is null
                       or v.department_id = current_user_department_id())
             )))
  );

-- =============================================================================
-- 12) Fix RLS — separar policies de write em INSERT/UPDATE/DELETE.
-- Policy FOR ALL faz OR no SELECT também, anulando os filtros de read.
-- =============================================================================
drop policy if exists p_auth_internal_write on fueling_authorization;
create policy p_auth_internal_ins on fueling_authorization for insert
  with check (current_user_role() in ('admin','usuario'));
create policy p_auth_internal_upd on fueling_authorization for update
  using (current_user_role() in ('admin','usuario'))
  with check (current_user_role() in ('admin','usuario'));
create policy p_auth_internal_del on fueling_authorization for delete
  using (current_user_role() in ('admin','usuario'));

drop policy if exists p_servauth_internal_write on service_authorization;
create policy p_servauth_internal_ins on service_authorization for insert
  with check (current_user_role() in ('admin','usuario'));
create policy p_servauth_internal_upd on service_authorization for update
  using (current_user_role() in ('admin','usuario'))
  with check (current_user_role() in ('admin','usuario'));
create policy p_servauth_internal_del on service_authorization for delete
  using (current_user_role() in ('admin','usuario'));

drop policy if exists p_fueling_internal_write on fueling;
create policy p_fueling_internal_ins on fueling for insert
  with check (current_user_role() in ('admin','usuario'));
create policy p_fueling_internal_upd on fueling for update
  using (current_user_role() in ('admin','usuario'))
  with check (current_user_role() in ('admin','usuario'));
create policy p_fueling_internal_del on fueling for delete
  using (current_user_role() in ('admin','usuario'));

drop policy if exists p_maint_write on maintenance;
create policy p_maint_ins on maintenance for insert
  with check (current_user_role() in ('admin','usuario'));
create policy p_maint_upd on maintenance for update
  using (current_user_role() in ('admin','usuario'))
  with check (current_user_role() in ('admin','usuario'));
create policy p_maint_del on maintenance for delete
  using (current_user_role() in ('admin','usuario'));

-- =============================================================================
-- 13) Força reload do schema cache do PostgREST
-- =============================================================================
notify pgrst, 'reload schema';

-- =============================================================================
-- FIM init.sql
-- =============================================================================
